name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # or any other version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch pytest

    - name: Run tests
      run: |
        pytest regression_test.py
